### ISSUE TITLE
Many edit tools do not handle Z altitude value nicely

### ISSUE THREAD

**Issue by haubourg** [qwat/QWAT#146]
- [x] add a default Z value option in the project - Part 1
- [x] - reshape tool looses atlitudes for all the whole geometry in some cases. In other cases, nan is in qgis buffer and leas to trouble with different data provider (postgres or shp for intance. 
- [x] - cut feature also looses Z
- [x] - default 0 altitude or -9999 should be used (signed integers in db might not like negative values anyway, 99999 might be better
- [x] Reshape tool don't take the z default value and keep "nan" value for the z coordinate
- [x] Extend with "node tool" take the value 0 for the z coordinate
- [x] Create a "point" memory layer with the Z/M coordinate doesn't work

- [x] Z default value is not honoured correctly for curved strings
 https://issues.qgis.org/issues/17574

- [x] Reshaping Curved geometries computes strange Z values
 https://issues.qgis.org/issues/17575 

- [x] creating new curve string does not uses default Z value and crashes https://issues.qgis.org/issues/17576
- [x]  copy / paste from 2d to 3D layer fails... Meh.. crashes now https://issues.qgis.org/issues/17577
- ~~[ ] handle NaN z values in QGIS, map it to default z in provider - Part 2 Pushed to 2018~~ > moved to a separate ticket

**Comment by haubourg** [comment]
Another one: copy / paste from 2d  to  3D layer fails.

**Comment by haubourg** [comment]
@wonder-sk Hi Martin, we found some available developpers to work on Z improvements. 
Should we add a default z value option at project level or general settings level? My opinion is that project level is the right place with SCR information.

**Comment by haubourg** [comment]
Work started. First PR's here:
https://github.com/qgis/QGIS/pull/3905/files

**Comment by haubourg** [comment]
Second part of the work started at nextGIS. They will spend 2 days on a RFC / QEP for a better null as NaN handling in QGIS

**Comment by ponceta** [comment]
For Pully we detected some issues using snapping on QGIS 2.18.X

If a 2D layer is in edit mode, snapping first element to a 3d point or 3d line will create a 3d object which will fail when saving to the DB. Same occurs in the opposite sense (3d -> 2D)

QGIS should be smart enough to allow only drawing corresponding geometries to DB layer geometries selected types AS loaded in QGIS.

**Comment by haubourg** [comment]
milestone pushed to mid 2017. Main part is done. Reviews welcome

**Comment by dsavary** [comment]
good news !

**Comment by dsavary** [comment]
I test the reshape tool in QGIS 2.99 (On Window). There is still the value "nan" for the Z when extending a line. The work of NextGIS is still in development phase ?

**Comment by haubourg** [comment]
hi Daniel, I can reproduce that, this is a full regression, which shouldn't have been possible with unit tests. 
It's possible that the click click node tool merge did break it all.  
@wonder-sk @simgislab : we have a full regression of default z value. Any idea what happened ? Do we really have units tests here?

**Comment by wonder-sk** [comment]
I have not been really involved in that work - I assume the reshape tool just was not updated within PR https://github.com/qgis/QGIS/pull/3905 to use the default Z value as well?

**Comment by dsavary** [comment]
I tested with QGIS 2.99 . 
Ok for the z  default value when you create a new feature.
However, some bugs : 

- Reshape tool don't take the z default value and keep "nan" value for the z coordinate
- Extend with "node tool" take the value 0 for the z coordinate 
demo GIF : [https://share.oslandia.net/public/bab7e8](https://share.oslandia.net/public/bab7e8)
- Create a "point" memory layer with the Z/M coordinate doesn't work
demo GIF : [https://share.oslandia.net/public/d4dca2](https://share.oslandia.net/public/d4dca2)

Somebody work on these problems ? NextGIS ?

**Comment by haubourg** [comment]
>Reshape tool don't take the z default value and keep "nan" value for the z coordinate
confirmed here in today's nightly
@wonder-sk can you put that in the bugfix list for the bugfix period ?

**Comment by haubourg** [comment]
Oops, @wonder-sk my previous comment was refering to the wrong issue. I meant:

>Extend with "node tool" take the value 0 for the z coordinate
Confirmed > I get a NaN until commit.

**Comment by haubourg** [comment]
> Reshape tool don't take the z default value and keep "nan" value for the z coordinate

I can't confirm that on a lineStringZ

**Comment by haubourg** [comment]
> Create a "point" memory layer with the Z/M coordinate doesn't work

this part works here, but node tool is not working on points. So no way to edit the node vertex panel. @wonder-sk  is that something you're aware of?

**Comment by wonder-sk** [comment]
> node tool is not working on points. So no way to edit the node vertex panel. @wonder-sk is that something you're aware of?

Sorry I am confused... what does not work? I have just tried and I can open vertex editor also for standalone points and modify their coordinates in the table...

**Comment by haubourg** [comment]
@wonder-sk , node tool for points works now, retesting with a newer version. Maybe it was a local problem. Sorry for the noise.

**Comment by haubourg** [comment]
Doing a full review again with version https://github.com/qgis/QGIS/commit/bcc8e90

Here is a checklist, let's try to declare atomic issues to keep track of that  : 

- [ ]  [#16887](https://issues.qgis.org/issues/16887) creating a memory scratch layer with Z/M values does not add Z/M to the layer. This confirms @dsavary  issue (Sorry, I thought you were saying that the option was missing, not that it failed)

- [ ] [#16888](https://issues.qgis.org/issues/16888) GPKG new layer creation UI does not have the Z/M dimension option

- [x] Extend with "node tool" take the value 0 for the z coordinate. This works here.
 
- [x] Reshape tool don't take the z default value and keep "nan" value for the z coordinate. Same, works here with a GPKG dataset.

**Comment by haubourg** [comment]
16887 and 16888 have just been fixed

**Comment by haubourg** [comment]
"Reshape tool don't take the z default value and keep "nan" value for the z coordinate." is working in master @dsavary can you give more information to reproduce ?

**Comment by haubourg** [comment]
same for  "Extend with "node tool" take the value 0 for the z coordinate." This works in master.

**Comment by haubourg** [comment]
@dsavary can we close that ?  I couldn't reproduce the two last checkboxes.

**Comment by dsavary** [comment]
@haubourg 
I make some tests on QGIS 3.0:
- memory layer : You can create a point layer with Z value, but you can't modify the Z coordinate , the feature keep the value "Nan" and of course don't take the default z value. ?
- postgis point layer : when you create a point, the z coordinate don't take the default z value, but keep Z = 0 . ?
- extend a line with "node tool" or with "reshape tool" take the z default value , It's a good news :) , but 
when we extend a line by snapping on 3d points. The vertex of the feature geometry should take the z coordinate of the points and not the default z value. 
This works like that when you add a new feature.

**Comment by haubourg** [comment]
Ok testing today with https://github.com/qgis/QGIS/commit/3d3b6d1

>memory layer : You can create a point layer with Z value, but you can't modify the Z coordinate , the feature keep the value "Nan" and of course don't take the default z value. ?

Confirmed 
![uploads/2bdfaec8-f184-43a8-bae5-d9a4c762fb84/image.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F2bdfaec8-f184-43a8-bae5-d9a4c762fb84%2Fimage.png)

 I asked Clément Marcel to throw an eye (@nouanda)


>postgis point layer : when you create a point, the z coordinate don't take the default z value, but keep Z = 0 . ?
Confirmed too. The z default value keeps regressing. Bad news. Subcontracting abroad is not a good option.


>extend a line with "node tool" or with "reshape tool" take the z default value , It's a good news :) , but
when we extend a line by snapping on 3d points. The vertex of the feature geometry should take the z coordinate of the points and not the default z value.
This works like that when you add a new feature.

Confirmed too. Did it work before ?

**Comment by dsavary** [comment]
@haubourg
No. But for QGIS 3.0 it would be great that the reshape tool take the z coordinate of snapping points (as default behavior and like the tool "create a feature" (line))

**Comment by haubourg** [comment]
PR here https://github.com/qgis/QGIS/pull/5239

**Comment by haubourg** [comment]
pr https://github.com/qgis/QGIS/pull/5823 for issues:

- Reshaping Curved geometries computes strange Z values https://issues.qgis.org/issues/17575

- creating new curve string does not uses default Z value and crashes https://issues.qgis.org/issues/17576

**Comment by haubourg** [comment]
PR #5823 merged, thanks @pblottiere @lbartoletti and @tudorbarascu for that!
