### ISSUE TITLE
QGIS : better handling forms - general ticket

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#229]
Improvements :

 - [x] Improve performances of current form lazy loading  > QGIS 3 https://github.com/qwat/QWAT/issues/154
 - [x] Relation reference widget - filter lists are not refreshed in attribute table form view https://github.com/qwat/QWAT/issues/190 
 - [x] improve QGIS to handle different layer definition sections : planned for end 2017 / early 2018: https://github.com/qwat/QWAT/issues/209

Bugfixes :

- [x] Widget constraints - performance and usability issues https://github.com/qwat/QWAT/issues/217
- [x] QGIS : Refresh entities count is a bit too aggressive https://github.com/qwat/QWAT/issues/214
- [x] Small bug on default value expression in forms https://github.com/qwat/QWAT/issues/232 > Impossible to evaluate such expression / ticket closed

QWAT specific :

- [x] Add constraints in forms https://github.com/qwat/QWAT/issues/158
