### ISSUE TITLE
QGIS : Better handling of altimetry - general ticket

### ISSUE THREAD

**Issue by ponceta** [qwat/QWAT#230]
Improvements : 
- [x] Maptools do not handle z values nicely https://github.com/qwat/QWAT/issues/146
- [x] Default z value handling in QGIS https://github.com/qwat/QWAT/issues/210

Bugfixes :
- [x] Important bug on reshape tool https://github.com/qwat/QWAT/issues/221
